Add `unsafe-to-chain-command` rule from upstream
foretagsplatsen/eslint-plugin-cypress pull request #90
Opened 2023-05-23 03:59 UTC by askoufis

Adding [the `unsafe-to-chain-command` from upstream](https://github.com/cypress-io/eslint-plugin-cypress/blob/master/docs/rules/unsafe-to-chain-command.md).

Fixes #87.

2023-06-06 03:59 UTC, askoufis commented
Hi @JanLayola.

Any chance I could get a review on this PR? Unfortunately it seems like the upstream are taking quite a while to migrate the repo to the cypress monorepo, so in the meantime this fork is the only option that works with ESLint 8.

Thanks.

2023-06-07 07:45 UTC, DamienCassou requested changes
Great job, thank you very much! I think the decomposition into atomic commits could be improved a little. I would probably have created 3 commits instead of 5:
1. Improve README.md
2. Add unsafe-to-chain-command rule
3. Add unsafe-to-chain-command rule to recommended config

Would you mind doing that please?

2023-06-07 23:49 UTC, askoufis commented
@DamienCassou I have rebased onto master and cleaned up/reorganized the commits.

2023-06-08 06:47 UTC, JanLayola approved these changes
> Reviewed 1 of 2 files at r1, 1 of 2 files at r3, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @askoufis)



<!-- Sent from Reviewable.io -->

2023-06-08 07:32 UTC, DamienCassou approved these changes
Awesome, thank you very much!

2023-06-08 07:38 UTC, merged

2023-06-08 07:40 UTC, DamienCassou commented
I reordered the commit and moved the new line in the table of the README to "Add unsafe-to-chain-command rule to recommended config" (I forgot to change the commit message accordingly though).

Thank you for your work!

2023-06-14 00:15 UTC, askoufis commented
Could this change be released please? Would be much appreciated ❤️

2023-11-23 00:26 UTC, askoufis commented
@DamienCassou @JanLayola Could this change please be released? Thanks.